### ISSUE TITLE
Using teamID + uid as membership identifier

### ISSUE THREAD

**Issue by nbcp** [nbcp/leaderboard#3]
Change membership collection id from uid to teamId + uid.
This would allow team leads to be approvers of multiple teams.

**Changes to be considered:**
- [x] Security rules - update logic to determine who is a team lead #7
- [x] Manage Team Page - add dropdown to switch across teams #9
- [x] Join Team Page - membership creation to use teamId + uid as identifier #8

**Comment by nbcp** [comment]
closed in ac2f8b5
