### ISSUE TITLE
Quests Standardization

### ISSUE THREAD

**Issue by nbcp** [nbcp/leaderboard#5]
- [x] Create script to upload standardize quests
- [x] Display category selection based from questCategories collection #10 
- [x] Standardized quest frontend changes #11
- [x] Standardized quest collection and service #13

**Comment by nbcp** [comment]
closed in ac2f8b5
